### ISSUE TITLE
 Implement Product Store Creation and Management Feature

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/company#1]
The current functionality for creating and managing product stores lacks user-centric design and robustness, hindering effective management of brand-specific inventory, orders, and product configurations in the OMS. To address these limitations and provide users with a more intuitive and efficient experience, we should revamp the product store creation and management functionality.

Please refer to [UI design](https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=29762%3A20877&mode=design&t=uk5PatOee1gRCEj3-1) and [user manual](https://docs.hotwax.co/user-guides/administration/company) for the implementation.

**Comment by Adameddy26** [comment]
Verified the changes and are working fine. Hence, closing it.
