### ISSUE TITLE
Add support to redirect user to facilities list page with product store filter

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#10]
## What is the motivation for adding/enhancing this feature?

When user click on the facilities count chip on the product store list item, he shoud be redirected to the facilities list page in facility app with the selected product store filter applied.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by amansinghbais** [comment]
Fixed here: https://github.com/hotwax/company/issues/7

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.0.0. Hence, closing it.
https://jam.dev/c/b5718dce-053e-41c6-abc6-c31190297632
