### ISSUE TITLE
Avoid calling api in case productStore setting value is not changed

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#15]
## What is the motivation for adding/enhancing this feature?

When user hit enter to update product store setting enums in case value setting value is not changed.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v1.0.0. Hence, closing this ticket
