### ISSUE TITLE
Use loader where ever needed in the app

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#18]
## What is the motivation for adding/enhancing this feature?

Loader should be displayed in actions where api calls are being made to inform user that some action is in progress.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v1.0.0. Hence, closing this ticket
