### ISSUE TITLE
Add manifest file along with all the required icons

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#21]
## What is the motivation for adding/enhancing this feature?

We should use icons of different sizes and a manifest file to map them to the screen size for better visibility.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
@amansinghbais : Please take necessary action on this ticket.
