### ISSUE TITLE
Change the login api's component and improve logic to fetch enums

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#27]
## What is the motivation for adding/enhancing this feature?

- We should use login api's from the Admin component itself.
- Improved logic to fetch enumeration for product identifications.
- Fix typo in translation entry of company text.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
@amansinghbais Please take necessary action on this ticket.
