### ISSUE TITLE
Improve routing to access Add Configurations page, and create product store flow.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#6]
## What is the motivation for adding/enhancing this feature?

- User could only access "Add configurations" when he is coming from the "Create product store" page.
- Redirect to store list page from "Add configurations" page on hitting ion-back-button.
- Improve the helper text for the productStoreId input on create product store page.
- Fix timezone fetching error.
- Show server error message dynamically when creating product store with duplicate id.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v1.0.0. Hence, closing this ticket.
