### ISSUE TITLE
Redirect user to facilities list page with product store filter applied on click facility count chip on the product store list page.

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#7]
## What is the motivation for adding/enhancing this feature?

When user click on the facilities count chip in product store list item in product store list page. The user should be redirected to the facilities list page in facilities app and current product store filter should be applied so as to show only the facilities associated in that product store.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v1.0.0. Hence, closing it.
https://jam.dev/c/b5718dce-053e-41c6-abc6-c31190297632
