### ISSUE TITLE
Add SSO support

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/company#9]
## What is the motivation for adding/enhancing this feature?

Enable SSO in compnay app using launchpad, use the ofbiz token to login into launchpad

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the changes and are working fine in release v1.0.0. Hence, closing this ticket
